"""Add notification_id to intake

Revision ID: 10e70302d7c7
Revises: 963cf0c4ade8
Create Date: 2026-02-18 23:08:01.380163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e70302d7c7'
down_revision = '963cf0c4ade8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'notifications', ['notification_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notification_id')

    # ### end Alembic commands ###
