"""Update Intake relationships

Revision ID: 18e5e065f082
Revises: a94086ca681f
Create Date: 2026-02-15 14:47:37.970302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18e5e065f082'
down_revision = 'a94086ca681f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('intake_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'medicine_schedule', ['scheduled_id'], ['id'])
        batch_op.drop_column('schedule_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('notifications_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'medicine_schedule', ['scheduled_id'], ['id'])
        batch_op.drop_column('schedule_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_ibfk_1'), 'medicine_schedule', ['schedule_id'], ['id'])
        batch_op.drop_column('scheduled_id')

    with op.batch_alter_table('intake', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('intake_ibfk_2'), 'medicine_schedule', ['schedule_id'], ['id'])
        batch_op.drop_column('scheduled_id')

    # ### end Alembic commands ###
