"""Revise slots to 4-day cycle and add schedule date

Revision ID: 48850bfac91a
Revises: 8e7385d2b26f
Create Date: 2026-03-03 11:19:08.110261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48850bfac91a'
down_revision = '8e7385d2b26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('tuesday')
        batch_op.drop_column('sunday')
        batch_op.drop_column('monday')
        batch_op.drop_column('friday')
        batch_op.drop_column('saturday')
        batch_op.drop_column('thursday')
        batch_op.drop_column('wednesday')

    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('slot_in_day', sa.Integer(), nullable=False))
        batch_op.drop_column('period')
        batch_op.drop_column('day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', mysql.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('period', mysql.VARCHAR(length=2), nullable=False))
        batch_op.drop_column('slot_in_day')
        batch_op.drop_column('day_number')

    with op.batch_alter_table('medicine_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wednesday', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('thursday', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('saturday', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('friday', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('monday', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sunday', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tuesday', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
