"""add is_active to schedules

Revision ID: 963cf0c4ade8
Revises: 18e5e065f082
Create Date: 2026-02-15 20:08:52.791493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963cf0c4ade8'
down_revision = '18e5e065f082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_schedule', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
